# -*- coding: utf-8 -*-
"""derma test

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HkizRxvqRir6UDmyPJnU20l6sKxCRdF
"""

# ============================================
# 📦 SETUP
# ============================================
!pip install -q torch torchvision timm gradio

import torch
import torch.nn as nn
from torchvision import models, transforms
from PIL import Image
import gradio as gr
import os

# ============================================
# ⚙️ MOUNT DRIVE AND LOAD MODEL
# ============================================
from google.colab import drive
drive.mount('/content/drive')

MODEL_PATH = "/content/drive/MyDrive/Derm_Model_Training/best_model.pth"
# Define your class names (same order as during training)
classes = [
    "Acne",
    "Basal Cell Carcinoma",
    "Eczema",
    "Melanoma",
    "Psoriasis",
    "Rosacea",
    "Urticaria",
    "Vitiligo",
]

# ============================================
# 🧠 LOAD TRAINED MODEL
# ============================================
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = models.efficientnet_b3(weights=None)  # structure only
in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, len(classes))
model.load_state_dict(torch.load(MODEL_PATH, map_location=device))
model = model.to(device)
model.eval()

print("✅ Model loaded successfully!")

# ============================================
# 🖼️ DEFINE TRANSFORMS FOR TEST IMAGE
# ============================================
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406],
                         [0.229, 0.224, 0.225])
])

# ============================================
# 🔍 PREDICTION FUNCTION
# ============================================
def predict_image(img):
    img = transform(img).unsqueeze(0).to(device)
    with torch.no_grad():
        outputs = model(img)
        probs = torch.softmax(outputs, dim=1)
        _, pred_idx = torch.max(probs, dim=1)
        pred_class = classes[pred_idx.item()]
        confidence = probs[0][pred_idx].item()
    return {pred_class: float(confidence)}

# ============================================
# 🚀 GRADIO INTERFACE FOR UPLOAD & PREDICTION
# ============================================
demo = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pil", label="Upload a skin image"),
    outputs=gr.Label(num_top_classes=3, label="Predicted Disease"),
    title="🩺 Dermatology AI Classifier",
    description="Upload a skin image and the model will predict the likely disease."
)

demo.launch(debug=False)